-- ################ CLASE 2 - indices: ################ --
-- Crear el usuario con el nombre de la sesion, 
-- todo esto desde el usuario de sistema:
CREATE USER USUARIO_V_N2_P2_C1 IDENTIFIED BY ASDFG1234
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

-- Otorgar recursos y conexión:
GRANT CONNECT, RESOURCE TO USUARIO_V_N2_P2_C1;

-- guardar y conectar al usuario USUARIO_V_N2_P2_C1
-- segun el profe, el nombre de las tablas siempres es en plural
-- NUMBER -> para numeros
-- VARCHAR2 -> textos
-- DATE -> fechas
-- CHAR -> textos con largo definido e invariable

CREATE TABLE PAISES (
  ID_PAIS NUMBER NOT NULL,
  NOMBRE VARCHAR2(70) NOT NULL,
  CONSTRAINT PK_PAIS PRIMARY KEY(ID_PAIS)
);
-- REVISAR LAS RESTRICCIONS:
SELECT * FROM USER_CONSTRAINTS;

CREATE  TABLE REGIONES(
  ID_REGION NUMBER(3) NOT NULL,
  NOMBRE VARCHAR(80) NOT NULL,
  PAIS NUMBER NOT NULL,
  POBLACION NUMBER(9) NOT NULL,
  NOMBRE_CAPITAL VARCHAR(70) NOT NULL,
  CONSTRAINT PK_REGION PRIMARY KEY(ID_REGION),
  CONSTRAINT FK_REGION FOREIGN KEY(PAIS) REFERENCES PAISES(ID_PAIS),
  CONSTRAINT CHK_ID_REGION CHECK(ID_REGION > 0),
  CONSTRAINT UNQ_NOMBRE_CAPITAL UNIQUE(NOMBRE_CAPITAL)
);

-- INSERTAR DATOS:

INSERT ALL 
  INTO PAISES VALUES(1, 'Chile')
  INTO PAISES VALUES(2, 'Argentina')
  INTO PAISES VALUES(3, 'Peru')
  INTO PAISES VALUES(4, 'Ecuador')
  INTO REGIONES VALUES(1, 'Region Metropolitana',1,10000000,'Santiago')
  INTO REGIONES VALUES(2, 'Region de Ohiggins',1,600000,'Rancagua')
  INTO REGIONES VALUES(3, 'Region de los Lagos',1,700000,'Puerto Montt')
  SELECT * FROM DUAL;


CREATE TABLE PERSONAS (
  RUT VARCHAR(13) NOT NULL,
  PRIMER_NOMBRE VARCHAR(10) NOT NULL,
  SEGUNDO_NOMBRE VARCHAR(20),
  PRIMER_APELLIDO VARCHAR(15) NOT NULL,
  SEGUNDO_APELLIDO VARCHAR(13),
  FECHA_NACIMIENTO DATE,
  DIRECCION VARCHAR(100) NOT NULL,
  REGION NUMBER(3),
  CONSTRAINT PK_PERSONA PRIMARY KEY(RUT),
  CONSTRAINT FK_PERSONA_REGION FOREIGN KEY(REGION) REFERENCES REGIONES(ID_REGION)
)

