-- ################ CLASE 3 - : ################ --

-- Bases de datos estructuradas N2-P14-C1 --
GRANT CONNECT, RESOURCE, CREATE SYNONYM, CREATE ANY INDEX TO USUARIO_N2_P14_C1;

CREATE TABLE REGIONES(
  ID_REGION NUMBER(3) NOT NULL,
  NOMBRE VARCHAR(70) NOT NULL,
  CONSTRAINT PK_REGION PRIMARY KEY(ID_REGION),
  CONSTRAINT CHK_ID_REGION CHECK(ID_REGION > 0),
  CONSTRAINT CHK_NOMBRE_REGION CHECK(LENGTH(NOMBRE) >= 3)
);

-- revisar las RESTRICCIONes:
SELECT * FROM USER_CONSTRAINTS;

-- adicional:
GRANT CREATE CLUSTER, CREATE INDEXTYPE, CREATE OPERATOR,
CREATE PROCEDURE, CREATE SEQUENCE, CREATE TABLE, CREATE TRIGGER, CREATE TYPE
TO RECURSOS;

-- CREAR LA TABLA EMPLEADOS:
CREATE TABLE EMPLEADOS(
  ID_EMPLEADO NUMBER(6) NOT NULL,
  RUT VARCHAR(13) NOT NULL,
  PRIMER_NOMBRE VARCHAR(15) NOT NULL,
  SEGUNDO_NOMBRE VARCHAR(15),
  PRIMER_APELLIDO VARCHAR(15) NOT NULL,
  SEGUNDO_APELLIDO VARCHAR(15),
  REGION NUMBER(3) NOT NULL,
  DIRECCION VARCHAR(100) NOT NULL,
  CORREO VARCHAR(60) NOT NULL,
  CONSTRAINT PK_EMPLEADOS PRIMARY KEY(ID_EMPLEADO),
  CONSTRAINT FK_REGION_EMPLEADO FOREIGN KEY(REGION) REFERENCES REGIONES(ID_REGION),
  CONSTRAINT UNQ_RUT_EMPLEADO UNIQUE(RUT),
  CONSTRAINT UNQ_CORREO_EMPLEADO UNIQUE(CORREO),
  CONSTRAINT CHK_RUT_EMPLEADO CHECK(LENGTH(RUT) > 8),
  CONSTRAINT CHK_PRIMER_NOMBRE CHECK(LENGTH(PRIMER_NOMBRE) > 3),
  CONSTRAINT CHK_PRIMER_APELLIDO CHECK(LENGTH(PRIMER_APELLIDO) > 3),
  CONSTRAINT CHK_DIRECCION CHECK(LENGTH(DIRECCION) > 8),
  CONSTRAINT CHK_CORREO CHECK(LENGTH(CORREO) > 8),
  CONSTRAINT CHK_ID_EMPLEADO CHECK(LENGTH(ID_EMPLEADO) > 0)
);

-- crear indice para efectos de prueba: ---
CREATE INDEX IND_APELLIDO_EMPLEADO ON EMPLEADOS(PRIMER_APELLIDO);

-- CONSULTAR POR INDICES:
SELECT ¨ FROM ALL_INDEXES;

SELECT * FROM ALL_INDEXES WHERE OWNER LIKE 'USUARIO_N2_P14_C1';

-- ELIMINAR INDICE:
DROP INDEX IDX_APELLIDO_EMPLEADO;

-- CREAR UN SINÓNIMO PARA UNA TABLA:
CREATE SYNONYM EMP FOR EMPLEADOS;
-- BORRAR SYNONYM:
DROP SYNONYM EMP;

-- VER TODOS LOS SYNONYM:
SELECT * FROM ALL_SYNONYMS;
SELECT * FROM ALL_SYNONYMS WHERE OWNER LIKE 'USUARIO_N2_P14_C1';

